services:
  nodeapp:
    build: .
    container_name: nodeapp
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_SQLITE_PATH: "/db/database.db"
    volumes:
      - sqlite_data:/db

volumes:
  sqlite_data:
